services:
  development:
    container_name: postgres-devel
    image: postgres:alpine
    env_file:
      - ./.env
    ports:  
      - ${POSTGRES_PORT}:5432
    volumes:
      - ../data/devel/postgres:/var/lib/postgresql/data